account/urls.py
from django.urls import path
from account import views  
from django.contrib.auth.decorators import login_required

urlpatterns = (
    path('', views.home, name='home'), 
    path('login/', views.loginacc, name='loginacc'), 
    path('login/admin', views.loginadmin, name='loginadmin'), 
    # path('login/', views.CustomLoginView.as_view(), name='login'),
    path('forgotacc/', views.forgot_acc, name='forgot_acc'), 
    path('token/', views.logintoken, name='logintoken'), 
    path('resend_token/', views.resend_token, name='resend_token'), 
    path('regis/', views.regis, name='regis'),   
    path('edit/<str:memberid>/', views.editmember, name='editmember'),
    path('logout/', views.logout_view, name='logout'),
    # path('edit/<str:memberid>/', views.editmember, name='editmember'),
    path('update/<str:memberid>/', views.update, name='update'),
    path('memberdetail/<str:memberid>/', views.memberdetail, name='memberdetail'),
    path('updatememberdetail/<str:memberid>/', views.update_member_detail, name='updatememberdetail'),
    path('edit-operator/<str:memberid>/', views.editoperator, name='editoperator'),
    path('delete/member/<str:memberid>/', views.destroymember, name='destroymember'),
    path('delete/class/<str:classid>/', views.destroyclass, name='destroyclass'),
    path('delete/course/<str:courseid>/', views.destroycourse, name='destroycourse'),
    path('delete/venue/<str:venuename>/', views.destroyvenue, name='destroyvenue'),
    path('delete/instructor/<str:courseid>/<str:instructor>/', views.destroyinstructor, name='destroyinstructor'),
    path('delete/assistant/<str:courseid>/<str:assistant>/', views.destroyassistant, name='destroyassistant'),
    path('updatoperatorv1/<str:memberid>/', views.updateoperatorv1, name='updateoperatorv1'),
    path('updatoperatorv2/<str:memberid>/', views.updateoperatorv2, name='updateoperatorv2'),
    path('regisoperator/', views.regisoperator, name='regisoperator'),
    path('showmember/', views.showmember, name='showmember'),
    path('editclass/<str:classid>/', views.editclass, name='editclass'),
    path('editcourse/<str:courseid>/', views.editcourse, name='editcourse'),
    path('editvenue/<str:venuename>/', views.editvenue, name='editvenue'),
    path('editinstructor/<str:courseid>/<str:instructor>/', views.editinstructor, name='editinstructor'),
    path('editassistant/<str:courseid>/<str:assistant>/', views.editassistant, name='editassistant'),
)

course/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("class/addclass/", views.addclass, name='addclass'),
    path("course/addcourse", views.addcourse, name='addcourse'),
    path("course/certif_instructor", views.addcertif_instructor, name='addcertif_instructor'),
    path("course/certif_assistant", views.addcertif_assistant, name='addcertif_assistant'),
    path("venue/addvenue", views.addvenue, name='addvenue'),
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language
from django.conf.urls.static import static

from webapp import settings

# URL patterns dasar tanpa prefix bahasa
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('account.urls')),
    path("", include('booking.urls')),
    path("", include('course.urls')),
    path('set-language/', set_language, name='set_language'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# URL patterns dengan prefix bahasa (i18n)
urlpatterns += i18n_patterns(
    path("", include('account.urls')),
    path("", include('booking.urls')), # Mengharuskan prefix bahasa di semua URL
    path("", include('course.urls'))
)

account/models.py
from datetime import datetime, timedelta
from django.db import models
from django.core.validators import RegexValidator
import string
import random

# Admin
class Users(models.Model):
    userid = models.CharField(primary_key=True, max_length=5)
    username = models.CharField(max_length=50)
    usermail = models.EmailField(unique=True, max_length=255, null=False, blank=False, default='example@gmail.com')
    usergroup = models.CharField(max_length=1)
    usergrade = models.IntegerField(blank=True, default='')
    userdesc = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return str(self.userid)

    class Meta:
        db_table = 'users'
        verbose_name_plural = "Users"

# Member
def generate_member_id(ktpname):
    while True:
        prefix = ktpname[:3].upper()
        rand_num = ''.join(random.choices(string.digits, k=9))
        parity = ''.join(random.choices(string.ascii_uppercase, k=3))
        member_id = f"{prefix}{rand_num[:3]}{parity[0]}{rand_num[3:6]}{parity[1]}{rand_num[6:]}{parity[2]}" 
        if not Member.objects.filter(memberid=member_id).exists():  # Check if the ID is unique
            return member_id

class Member(models.Model):
    letter_validator = RegexValidator(regex=r'^[a-zA-Z\s]+$', message='Only letters and spaces are allowed')
    letterv2_validator = RegexValidator(regex=r'^[a-zA-Z]+$', message='Only letters are allowed, without space')

    memberid = models.CharField(primary_key=True, max_length=15)
    emailmain = models.EmailField(unique=True, max_length=255, null=False, blank=False, default='example@gmail.com')
    accountname = models.CharField(unique=True, max_length=255, default='default_value', validators=[letterv2_validator])
    password = models.CharField(max_length=30)

    ktpname = models.CharField(max_length=100, validators=[letter_validator])
    firstname = models.CharField(max_length=50, validators=[letter_validator])
    middlename = models.CharField(max_length=20, blank=True, null=True, validators=[letter_validator])
    lastname = models.CharField(max_length=50, validators=[letter_validator])
    memberstatus = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.accountname = self.accountname.lower()
        self.ktpname = self.ktpname.lower()
        self.firstname = self.firstname.lower()
        self.middlename = self.middlename.lower() if self.middlename else self.middlename
        self.lastname = self.lastname.lower()

        if not self.memberid:
            self.memberid = generate_member_id(self.ktpname)

        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.memberid

    class Meta:
        db_table = 'member'
        verbose_name_plural = "Members"

# Member Detail
class Memberdetail(models.Model):
    letter_validator = RegexValidator(regex=r'^[a-zA-Z\s]+$', message='Only letters and spaces are allowed')
    number_validator = RegexValidator(regex=r'^\d+$', message='Only numbers are allowed')

    memberid = models.OneToOneField(Member, on_delete=models.CASCADE, db_column='memberid', null=True)  # Remove primary_key=True
    callsign = models.CharField(max_length=25, blank=True, default='', validators=[letter_validator])
    participant = models.IntegerField()
    instructor = models.IntegerField()
    author = models.IntegerField()
    referral = models.IntegerField()
    dob = models.DateField()
    ktpnumber = models.CharField(max_length=30, blank=True, default='', validators=[number_validator])
    taxid = models.CharField(max_length=30, blank=True, default='', validators=[number_validator])
    join_date = models.DateField()
    emailmain = models.EmailField(max_length=50)
    emailalt = models.EmailField(max_length=50, blank=True, default='')
    whatsapp = models.CharField(max_length=20, blank=True, default='', validators=[number_validator])
    phone = models.CharField(max_length=20, blank=True, default='', validators=[number_validator])
    telegram = models.CharField(max_length=20, blank=True, default='')
    referralid = models.CharField(max_length=15, blank=True, default='')
    paidclass = models.PositiveIntegerField(default=0, null=True)
    freeclass = models.PositiveIntegerField(default=0, null=True)
    pointtotal = models.PositiveIntegerField(db_column='pointTotal', default=0, null=True)  # Field name made lowercase.
    pointredeem = models.PositiveIntegerField(db_column='pointRedeem', default=0, null=True)  # Field name made lowercase.

    def save(self, *args, **kwargs):
        if self.callsign:
            self.callsign = self.callsign.lower()

        if self.referral:  # If referral is set, assign the memberid's value
            self.referralid = self.memberid.memberid  # Use the actual memberid string
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.memberid)  # Return the memberid from the related Member instance

    class Meta:
        db_table = 'memberdetail'
        verbose_name_plural = "Member Detail"
        unique_together = (('ktpnumber', 'emailmain'),)

# class OtpToken(models.Model):
#     member = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     otp = models.CharField(max_length=8, default=secrets.token_hex(4))
#     created_at = models.DateTimeField(auto_now_add=True)
#     expires_at = models.DateTimeField(blank=True, null=True)

#     def __str__(self):
#         return self.member.memberid

account/forms.py
from django import forms  
from account.models import Member, Memberdetail  # Ensure you import the correct model
from django.forms import ModelForm

class MemberForm(forms.ModelForm): 
    MEMBER_STATUS_CHOICES = [
        (True, 'Active'),
        (False, 'Inactive'),
    ]

    # Use a ChoiceField for memberstatus
    memberstatus = forms.ChoiceField(
        choices=MEMBER_STATUS_CHOICES,
        widget=forms.Select(attrs={'class': 'form-select'}),  # Adding the class for styling
        label="Current Member Status"
    )

    class Meta:  
        model = Member 
        fields = ['ktpname', 'emailmain', 'accountname', 'password', 'firstname', 'middlename', 'lastname', 'memberstatus'] 
        widgets = { 
            'ktpname': forms.TextInput(attrs={'class': 'form-control'}),
            'emailmain': forms.EmailInput(attrs={'class': 'form-control'}),
            'accountname': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'firstname': forms.TextInput(attrs={'class': 'form-control'}),
            'middlename': forms.TextInput(attrs={'class': 'form-control'}),
            'lastname': forms.TextInput(attrs={'class': 'form-control'}),
            # 'memberstatus' widget is already defined above, so no need to include it here
        }

    # def clean_memberstatus(self):
    #     memberstatus = self.cleaned_data.get('memberstatus')
    #     if memberstatus == 'Yes':
    #         return 1  # Convert 'Yes' to 1
    #     elif memberstatus == 'No':
    #         return 0  # Convert 'No' to 0
    #     raise forms.ValidationError('This field is required.')

    def clean_ktpname(self):
        ktpname = self.cleaned_data.get('ktpname', '').strip()  # Strip whitespace
        if not all(char.isalpha() or char.isspace() for char in ktpname):
            raise forms.ValidationError('KTP name can only contain letters and spaces.')
        return ktpname

    def clean_firstname(self):
        firstname = self.cleaned_data.get('firstname')
        if not firstname.isalpha():
            raise forms.ValidationError('First name can only contain letters.')
        return firstname

    def clean_middlename(self):
        middlename = self.cleaned_data.get('middlename')
        if middlename:
            if not all(char.isalpha() or char.isspace() for char in middlename):
                raise forms.ValidationError('Middle name can only contain letters.')
        else:
            return ''
        return middlename

    def clean_lastname(self):
        lastname = self.cleaned_data.get('lastname')
        if not lastname.isalpha():
            raise forms.ValidationError('Last name can only contain letters.')
        return lastname
    
    def clean_accountname(self):
        accountname = self.cleaned_data.get('accountname')
        if accountname and not accountname.islower():
            raise forms.ValidationError("Account Name must be in lowercase")
        return accountname

class RegisForm(forms.ModelForm): 
    class Meta:  
        model = Member 
        fields = ['ktpname', 'emailmain', 'accountname', 'password', 'firstname', 'middlename', 'lastname', 'memberstatus'] 
        widgets = { 
            'ktpname': forms.TextInput(attrs={'class': 'form-control'}),
            'emailmain': forms.EmailInput(attrs={'class': 'form-control'}),
            'accountname': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'firstname': forms.TextInput(attrs={'class': 'form-control'}),
            'middlename': forms.TextInput(attrs={'class': 'form-control'}),
            'lastname': forms.TextInput(attrs={'class': 'form-control'}),
            # 'memberstatus' widget is already defined above, so no need to include it here
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.memberstatus = False  # Set memberstatus to False by default
        if commit:
            user.save()
        return user

    def clean_ktpname(self):
        ktpname = self.cleaned_data.get('ktpname', '').strip()  # Strip whitespace
        if not all(char.isalpha() or char.isspace() for char in ktpname):
            raise forms.ValidationError('KTP name can only contain letters and spaces.')
        return ktpname

    def clean_firstname(self):
        firstname = self.cleaned_data.get('firstname')
        if not firstname.isalpha():
            raise forms.ValidationError('First name can only contain letters.')
        return firstname

    def clean_middlename(self):
        middlename = self.cleaned_data.get('middlename')
        if middlename:
            if not all(char.isalpha() or char.isspace() for char in middlename):
                raise forms.ValidationError('Middle name can only contain letters.')
        else:
            return ''
        return middlename

    def clean_lastname(self):
        lastname = self.cleaned_data.get('lastname')
        if not lastname.isalpha():
            raise forms.ValidationError('Last name can only contain letters.')
        return lastname
    
    def clean_accountname(self):
        accountname = self.cleaned_data.get('accountname')
        if accountname and not accountname.islower():
            raise forms.ValidationError("Account name must be in lowercase")
        return accountname

class MemberDetailForm(forms.ModelForm):
            
    class Meta:
        model = Memberdetail
        fields = ['memberid', 'callsign', 'participant', 'instructor', 'author', 'referral', 'dob', 'ktpnumber',
            'taxid', 'join_date', 'emailmain', 'emailalt', 'whatsapp', 'phone', 'telegram',
            'referralid', 'paidclass', 'freeclass', 'pointtotal', 'pointredeem']
        widgets = { 
            'memberid': forms.TextInput(attrs={'class': 'form-control'}),
            'callsign': forms.TextInput(attrs={'class': 'form-control'}),
            'participant': forms.TextInput(attrs={'class': 'form-control'}),
            'instructor': forms.TextInput(attrs={'class': 'form-control'}),
            'referral': forms.TextInput(attrs={'class': 'form-control'}),
            'dob': forms.DateInput(attrs={'class': 'form-control'}),
            'ktpnumber': forms.TextInput(attrs={'class': 'form-control'}),
            'taxid': forms.TextInput(attrs={'class': 'form-control'}),
            'join_date': forms.DateInput(attrs={'class': 'form-control'}),
            'emailmain': forms.EmailInput(attrs={'class': 'form-control'}),
            'emailalt': forms.EmailInput(attrs={'class': 'form-control'}),
            'whatsapp': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'telegram': forms.TextInput(attrs={'class': 'form-control'}),
            'referralid': forms.TextInput(attrs={'class': 'form-control'}),
            'paidclass': forms.TextInput(attrs={'class': 'form-control'}),
            'freeclass': forms.TextInput(attrs={'class': 'form-control'}),
            'pointtotal': forms.TextInput(attrs={'class': 'form-control'}),
            'pointredeem': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_emailalt(self):
        emailmain = self.cleaned_data.get('emailmain')
        emailalt = self.cleaned_data.get('emailalt')

        if emailmain and emailalt and emailmain == emailalt:
            raise forms.ValidationError("Email Alternative must be different from Email Main.")
        return emailalt
        
    # def clean(self):
    #     cleaned_data = super().clean()  # Call the parent class's clean method
    #     fields_to_clean = ['callsign', 'emailalt', 'taxid', 'whatsapp']

    #     for field in fields_to_clean:
    #         value = cleaned_data.get(field)  # Access cleaned_data for the field
    #         # Set field value to an empty string if it's None
    #         if value is None or value == '':
    #             self.add_error(field, 'Please fill out this field!')  # Use add_error to set the error message

    #     return cleaned_data  # Return the cleaned_data instead of a single value

account/templates/editmember.html
{% extends 'base.html' %}
{% load i18n %}  <!-- Load translation tags -->

{% block content %}
<div style="background: #FFF; position: fixed; left: 80%; padding: 10px; top: 85%; margin: 0;">
  <form action="{% url 'set_language' %}" method="POST">
    {% csrf_token %}
    <select name="language" class="form-select fw-bold" style="width: 150px; font-size: 16px; padding: 10px;" aria-label="{% trans 'Language' %}" onchange="this.form.submit()">
      <option value="en" {% if LANGUAGE_CODE == 'en' %}selected{% endif %}>English</option>
      <option value="id" {% if LANGUAGE_CODE == 'id' %}selected{% endif %}>Indonesian</option>
    </select>
    <input type="hidden" name="next" value="{{ request.path }}">
  </form>
</div>
  
<div class="container">
    <div style="margin-top: 50px;"> <!-- Atur jarak sesuai kebutuhan -->
        <h1>{% trans "Edit Profile" %}</h1>
    </div>
    <hr>
    <div class="row">
        <!-- left column -->
        <div class="col-md-3">
            <div class="text-center">
                <img src="//placehold.it/100" class="avatar img-circle" alt="avatar" style="margin-bottom: 20px;"> <!-- Added margin here -->
                <!-- <h6>Upload a different photo...</h6> -->
                
                <input type="file" class="form-control">
                {% if employee.memberstatus %}
                <a href="/memberdetail/{{ employee.memberid }}" class="btn btn-secondary mt-2">{% trans "View Member Detail" %}</a>
                {% endif %}
            </div>
        </div>
        
        <!-- edit form column -->
        <div class="col-md-9 personal-info">
            <!-- <div class="alert alert-info alert-dismissable">
                <a class="panel-close close" data-dismiss="alert">×</a> 
                <i class="fa fa-coffee"></i>
                This is an <strong>.alert</strong>. Use this to show important messages to the user.
            </div> -->

            <p></p>

            <div class="row" style="margin-bottom: 10px;">  <!-- Added row for layout -->
                <div class="col-md-6"> <!-- Column for Member Info -->
                    <h3>{% trans "Profile Information" %}</h3>
                </div>
            </div>
            
            <form class="form-horizontal" role="form" method="POST" action="{% url 'update' employee.memberid %}">
                {% csrf_token %}
                <div class="form-group mb-3">
                    <label class="col-lg-3 control-label">{% trans "Member ID" %}</label>
                    <div class="col-lg-8">
                        <input type="text" class="form-control" name="memberid" id="id_memberid" required maxlength="15" value="{{ employee.memberid }}" readonly/>    
                    </div>
                </div>

                <div class="form-group mb-3">
                    <label for="id_memberstatus" class="col-lg-3 control-label">{% trans "Current Member Status" %}</label>
                    <div class="col-lg-8">
                        <input type="text" class="form-control" 
                               value="{% if employee.memberstatus %}{% trans 'Active' %}{% else %}{% trans 'Inactive' %}{% endif %}" 
                               readonly>
                        <input type="hidden" name="memberstatus" value="{{ employee.memberstatus }}">
                    </div>
                </div>                
                
                <div class="form-group mb-3">
                    <label class="col-lg-3 control-label">{% trans "Email" %}</label>
                    <div class="col-lg-8">
                        <input type="email" class="form-control" name="emailmain" id="id_emailmain" required maxlength="100" value="{{ employee.emailmain }}" />
                    </div>
                </div>

                <div class="form-group mb-3">
                    <label class="col-lg-3 control-label">{% trans "Password" %}</label>
                    <div class="col-lg-8">
                        <input type="password" class="form-control" name="password" id="id_password" required maxlength="30" value="{{ employee.password }}" />
                    </div>
                </div>

                <div class="form-group mb-3">
                    <label class="col-lg-3 control-label">{% trans "Account Name" %}</label>
                    <div class="col-lg-8">
                        <input type="text" class="form-control" name="accountname" id="id_accountname" required maxlength="100" value="{{ employee.accountname }}" />
                        {% for error in form.accountname.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group mb-3">
                    <label class="col-lg-3 control-label">{% trans "KTP Name" %}</label>
                    <div class="col-lg-8">
                        <input type="text" class="form-control" name="ktpname" id="id_ktpname" required maxlength="100" value="{{ employee.ktpname }}" />
                        {% for error in form.ktpname.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group mb-3">
                    <label class="col-lg-3 control-label">{% trans "First Name" %}</label>
                    <div class="col-lg-8">
                        <input type="text" class="form-control" name="firstname" id="id_firstname" required maxlength="50" value="{{ employee.firstname }}" />
                        {% for error in form.firstname.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group mb-3">
                    <label class="col-lg-3 control-label">{% trans "Middle Name" %}</label>
                    <div class="col-lg-8">
                        <input type="text" class="form-control" name="middlename" id="id_middlename" maxlength="20" 
                               value="{{ employee.middlename|default:'' }}" />
                        {% for error in form.middlename.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
                
                <div class="form-group mb-3">
                    <label class="col-lg-3 control-label">{% trans "Last Name" %}</label>
                    <div class="col-lg-8">
                        <input type="text" class="form-control" name="lastname" id="id_lastname" required maxlength="50" value="{{ employee.lastname }}" />
                        {% for error in form.lastname.errors %}
                            <div class="text-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-5 control-label"></label>
                    <div class="col-md-8 d-flex justify-content-between">
                        <div>
                            <input type="submit" class="btn btn-primary me-2 mb-3" value="{% trans 'Save Changes' %}"> <!-- 'mb-3' adds bottom margin -->
                        </div>
                        <div>
                            <a href="{% url 'logout' %}" 
                            class="btn btn-danger me-2 mb-3" 
                            onclick="return confirm('{% trans 'Are you sure you want to logout?' %}');">
                            {% trans 'Logout' %}
                            </a>
                            <!-- 
                            <span></span>
                            <a href="/delete/{{ employee.memberid }}" class="btn btn-danger mb-3" onclick="return confirm('Are you sure you want to delete?');">Delete</a> -->
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div> 
</div>
{% endblock content %}

account/templates/registration.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}Login{% endblock %}

{% block content %}
<div style="background: #FFF; position: fixed; left: 80%; padding: 10px; top: 85%; margin: 0;">
  <form action="{% url 'set_language' %}" method="POST">
    {% csrf_token %}
    <select name="language" class="form-select fw-bold" style="width: 150px; font-size: 16px; padding: 10px;" aria-label="{% trans 'Language' %}" onchange="this.form.submit()">
      <option value="en" {% if LANGUAGE_CODE == 'en' %}selected{% endif %}>English</option>
      <option value="id" {% if LANGUAGE_CODE == 'id' %}selected{% endif %}>Indonesian</option>
    </select>
    <input type="hidden" name="next" value="{{ request.path }}">
  </form>
</div>

<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-10 col-lg-8 col-xl-6">
        <h1 class="fw-bold mb-2">{% trans "REGISTRATION" %}</h1>
        <hr>

        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <form method="POST" class="post-form" action="{% url 'regis' %}">
            {% csrf_token %}  

            <div class="mb-3">
                <label for="emailmain" class="form-label">Email</label>
                <input type="email" class="form-control" name="emailmain" id="id_emailmain" required>
                {% if form.emailmain.errors %}
                    {% for error in form.emailmain.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}   
            </div>         

            <div class="mb-3"> 
                <label for="password" class="form-label">{% trans "Password" %}</label>  
                {{ form.password }}   
            </div>
            

            <div class="mb-3">
                <label for="accountname" class="form-label">{% trans "Account Name" %}</label>
                <input type="text" class="form-control" name="accountname" id="id_accountname" required>
                {% if form.accountname.errors %}
                    {% for error in form.accountname.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>      

            <div class="mb-3">
                <label for="ktpname" class="form-label">{% trans "KTP Name" %}</label>
                {{ form.ktpname }} 
                {% if form.ktpname.errors %}
                    {% for error in form.ktpname.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>         

            <div class="mb-3"> 
                <label for="firstname" class="form-label">{% trans "First Name" %}</label>  
                {{ form.firstname }}   
                {% if form.firstname.errors %}
                    {% for error in form.firstname.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-3"> 
                <label for="middlename" class="form-label">{% trans "Middle Name" %}</label>  
                {{ form.middlename }}   
                {% if form.middlename.errors %}
                    {% for error in form.middlename.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="mb-3"> 
                <label for="lastname" class="form-label">{% trans "Last Name" %}</label>  
                {{ form.lastname }}   
                {% if form.lastname.errors %}
                    {% for error in form.lastname.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endif %}
            </div>

            <div class="d-grid">
                <button type="submit" class="btn btn-success btn-lg fw-bold" style="border-radius: 1rem;">{% trans "Sign Up" %}</button>  
            </div>

            <!-- Adding space below the submit button -->
            <div style="margin-top: 20px;"></div>

            <!-- Adding Login button -->
            <div class="d-grid mt-3">  
                <a href="/" class="btn btn-primary btn-lg fw-bold" style="background-color: #0e345c; border-radius: 1rem;">Login</a>  
            </div>
            
            <!-- Adding space below the submit button -->
            <div style="margin-top: 40px;"></div>

        </form>  
      </div>
    </div>
  </div>
</section>
{% endblock content %}