booking/urls.py
# booking/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('event/<str:event_id>/', views.event, name='booking_event'),
    path('booking/<str:event_id>/', views.booking_without_referral, name='booking_index'),
    path('booking/<str:event_id>/<str:referral_id>/', views.booking_with_referral, name='booking_with_referral'),
    # path('update_booking_status/', views.update_booking_status, name='update_booking_status'),
]

course/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("class/addclass/", views.addclass, name='addclass'),
    path("course/addcourse", views.addcourse, name='addcourse'),
    path("course/certif_instructor", views.addcertif_instructor, name='addcertif_instructor'),
    path("course/certif_assistant", views.addcertif_assistant, name='addcertif_assistant'),
    path("venue/addvenue", views.addvenue, name='addvenue'),
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language
from django.conf.urls.static import static

from webapp import settings

# URL patterns dasar tanpa prefix bahasa
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('account.urls')),
    path("", include('booking.urls')),
    path("", include('course.urls')),
    path('set-language/', set_language, name='set_language'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# URL patterns dengan prefix bahasa (i18n)
urlpatterns += i18n_patterns(
    path("", include('account.urls')),
    path("", include('booking.urls')), # Mengharuskan prefix bahasa di semua URL
    path("", include('course.urls'))
)

account/models.py
from datetime import datetime, timedelta
from django.db import models
from django.core.validators import RegexValidator
import string
import random

# Admin
class Users(models.Model):
    userid = models.CharField(primary_key=True, max_length=5)
    username = models.CharField(max_length=50)
    usermail = models.EmailField(unique=True, max_length=255, null=False, blank=False, default='example@gmail.com')
    usergroup = models.CharField(max_length=1)
    usergrade = models.IntegerField(blank=True, default='')
    userdesc = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return str(self.userid)

    class Meta:
        db_table = 'users'
        verbose_name_plural = "Users"

# Member
def generate_member_id(ktpname):
    while True:
        prefix = ktpname[:3].upper()
        rand_num = ''.join(random.choices(string.digits, k=9))
        parity = ''.join(random.choices(string.ascii_uppercase, k=3))
        member_id = f"{prefix}{rand_num[:3]}{parity[0]}{rand_num[3:6]}{parity[1]}{rand_num[6:]}{parity[2]}" 
        if not Member.objects.filter(memberid=member_id).exists():  # Check if the ID is unique
            return member_id

class Member(models.Model):
    letter_validator = RegexValidator(regex=r'^[a-zA-Z\s]+$', message='Only letters and spaces are allowed')
    letterv2_validator = RegexValidator(regex=r'^[a-zA-Z]+$', message='Only letters are allowed, without space')

    memberid = models.CharField(primary_key=True, max_length=15)
    emailmain = models.EmailField(unique=True, max_length=255, null=False, blank=False, default='example@gmail.com')
    accountname = models.CharField(unique=True, max_length=255, default='default_value', validators=[letterv2_validator])
    password = models.CharField(max_length=30)

    ktpname = models.CharField(max_length=100, validators=[letter_validator])
    firstname = models.CharField(max_length=50, validators=[letter_validator])
    middlename = models.CharField(max_length=20, blank=True, null=True, validators=[letter_validator])
    lastname = models.CharField(max_length=50, validators=[letter_validator])
    memberstatus = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.accountname = self.accountname.lower()
        self.ktpname = self.ktpname.lower()
        self.firstname = self.firstname.lower()
        self.middlename = self.middlename.lower() if self.middlename else self.middlename
        self.lastname = self.lastname.lower()

        if not self.memberid:
            self.memberid = generate_member_id(self.ktpname)

        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.memberid

    class Meta:
        db_table = 'member'
        verbose_name_plural = "Members"

# Member Detail
class Memberdetail(models.Model):
    letter_validator = RegexValidator(regex=r'^[a-zA-Z\s]+$', message='Only letters and spaces are allowed')
    number_validator = RegexValidator(regex=r'^\d+$', message='Only numbers are allowed')

    memberid = models.OneToOneField(Member, on_delete=models.CASCADE, db_column='memberid', null=True)  # Remove primary_key=True
    callsign = models.CharField(max_length=25, blank=True, default='', validators=[letter_validator])
    participant = models.IntegerField()
    instructor = models.IntegerField()
    author = models.IntegerField()
    referral = models.IntegerField()
    dob = models.DateField()
    ktpnumber = models.CharField(max_length=30, blank=True, default='', validators=[number_validator])
    taxid = models.CharField(max_length=30, blank=True, default='', validators=[number_validator])
    join_date = models.DateField()
    emailmain = models.EmailField(max_length=50)
    emailalt = models.EmailField(max_length=50, blank=True, default='')
    whatsapp = models.CharField(max_length=20, blank=True, default='', validators=[number_validator])
    phone = models.CharField(max_length=20, blank=True, default='', validators=[number_validator])
    telegram = models.CharField(max_length=20, blank=True, default='')
    referralid = models.CharField(max_length=15, blank=True, default='')
    paidclass = models.PositiveIntegerField(default=0, null=True)
    freeclass = models.PositiveIntegerField(default=0, null=True)
    pointtotal = models.PositiveIntegerField(db_column='pointTotal', default=0, null=True)  # Field name made lowercase.
    pointredeem = models.PositiveIntegerField(db_column='pointRedeem', default=0, null=True)  # Field name made lowercase.

    def save(self, *args, **kwargs):
        if self.callsign:
            self.callsign = self.callsign.lower()

        if self.referral:  # If referral is set, assign the memberid's value
            self.referralid = self.memberid.memberid  # Use the actual memberid string
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.memberid)  # Return the memberid from the related Member instance

    class Meta:
        db_table = 'memberdetail'
        verbose_name_plural = "Member Detail"
        unique_together = (('ktpnumber', 'emailmain'),)

# class OtpToken(models.Model):
#     member = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     otp = models.CharField(max_length=8, default=secrets.token_hex(4))
#     created_at = models.DateTimeField(auto_now_add=True)
#     expires_at = models.DateTimeField(blank=True, null=True)

#     def __str__(self):
#         return self.member.memberid

booking/models.py
from datetime import timedelta, datetime
from django.utils import timezone
from django.db import models
from account.models import Member
from course.models import Class

class DraftBooking(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    bookingid = models.CharField(max_length=50, unique=True)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    telegram = models.BooleanField(default=False)
    event = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, blank=True)
    referralid = models.ForeignKey(Member, on_delete=models.SET_NULL, null=True, blank=True)

    BOOKINGSTATUS_CHOICES = [
        ('active', 'Active'),
        ('expired', 'Expired'),
    ]
    bookingstatus = models.CharField(max_length=10, choices=BOOKINGSTATUS_CHOICES, default='active')
    # Perbaikan pada field memberstatus agar terhubung ke tabel Member
    memberstatus = models.ForeignKey(
        Member, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        related_name='member_bookings'  # Mengubah related_name agar lebih jelas
    )

    PAYMENTSTATUS_CHOICES = [
        ('completed', 'Completed'),
        ('pending', 'Pending'), # menunggu pembayaran
        ('cancelled', 'Cancelled'),
        ('onhold', 'On Hold'), # menunggu verifikasi pembayaran
    ]
    paymentstatus = models.CharField(max_length=10, choices=PAYMENTSTATUS_CHOICES, default='pending')

    created_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    payment_expires_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Booking ID: {self.bookingid}"

    def save(self, *args, **kwargs):
        if not self.id:
            last_booking = DraftBooking.objects.order_by('-id').first()
            self.id = (last_booking.id + 1) if last_booking else 1

        if not self.created_at:
            self.created_at = timezone.now()

        if not self.expires_at:
            # Ensure created_at is a datetime object before adding timedelta
            if isinstance(self.created_at, str):
                self.created_at = timezone.make_aware(datetime.strptime(self.created_at, "%Y-%m-%d %H:%M:%S"))
            self.expires_at = self.created_at + timedelta(minutes=10)

        if not self.payment_expires_at:
            if isinstance(self.created_at, str):
                self.created_at = timezone.make_aware(datetime.strptime(self.created_at, "%Y-%m-%d %H:%M:%S"))
            self.payment_expires_at = self.created_at + timedelta(minutes=10)

        # Jika referralid tidak ada, pastikan referral_name juga None
        if not self.referralid:
            self.referralid = None

        # Ensure expires_at is a datetime object for comparison
        if isinstance(self.expires_at, str):
            self.expires_at = timezone.make_aware(datetime.strptime(self.expires_at, "%Y-%m-%d %H:%M:%S"))
            
        if timezone.now() > self.expires_at:
            self.bookingstatus = 'expired'

        super(DraftBooking, self).save(*args, **kwargs)

    
    class Meta:
        unique_together = ('bookingid', 'id')
        db_table = 'draftbooking'
        verbose_name = 'Draft Booking'
        verbose_name_plural = 'Draft Bookings'

booking/forms.py
import random
import string
from django import forms
from django.shortcuts import get_object_or_404
from account.models import Member
from booking.models import DraftBooking
from django.forms import ModelForm

class DraftBookingForm(ModelForm):
    WHATSAPP_CHOICES = [
        (True, 'Yes'),
        (False, 'No'),
    ]

    # Use a ChoiceField for memberstatus
    telegram = forms.ChoiceField(
        choices=WHATSAPP_CHOICES,
        widget=forms.Select(attrs={'class': 'form-select'}),  # Adding the class for styling
        label="telegram Number"
    )

    # Tambahkan field memberstatus sebagai ModelChoiceField
    memberstatus = forms.ModelChoiceField(
        queryset=Member.objects.all(),
        required=False,
        empty_label="Not a Member"
    )

    class Meta:
        model = DraftBooking
        fields = ['name', 'email', 'phone', 'event', 'referralid', 'bookingid', 'telegram', 'memberstatus']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'event': forms.Select(),
            'referralid': forms.Select(attrs={'required': False}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['bookingid'].required = False
        self.fields['memberstatus'].required = False
        self.fields['referralid'].required = False
        # Pastikan field memberstatus menggunakan queryset yang benar
        self.fields['memberstatus'].queryset = Member.objects.all()

    def save(self, commit=True):
        instance = super().save(commit=False)

        # Generate bookingid if not provided
        if not instance.bookingid:
            event = self.cleaned_data.get('event')
            prefix = event.classid if event else ''
            random_code = ''.join(random.choices(string.ascii_uppercase, k=5))
            instance.bookingid = prefix[:3] + random_code

        # Perbaikan logika untuk memberstatus
        email = self.cleaned_data.get('email')
        try:
            member = Member.objects.get(emailmain=email)
            instance.memberstatus = member
        except Member.DoesNotExist:
            instance.memberstatus = None

        # Pastikan referralid None jika tidak ada
        if not self.cleaned_data.get('referralid'):
            instance.referralid = None
            instance.referral_name = None

        if commit:
            instance.save()
        return instance

booking/views.py
from datetime import timezone
from django.shortcuts import render, get_object_or_404, redirect
from course.models import Class
from account.models import Member
from django.http import Http404, HttpResponse
from .forms import DraftBookingForm
from django.contrib import messages
from django.utils.translation import gettext as _

def booking_with_referral(request, event_id, referral_id):
    print("referral_id", referral_id)
    try:
        event = Class.objects.get(classid=event_id)
        try:
            referral = Member.objects.get(memberid=referral_id)
        except Member.DoesNotExist:
            referral = None
    except Class.DoesNotExist:
        raise Http404(_("Event doesn't exist"))
    
    print("referral", referral)
        
    if request.method == "POST":
        form = DraftBookingForm(request.POST)
        print(form)
        if form.is_valid():
            draft_booking = form.save(commit=False)
            try:
                member = Member.objects.get(emailmain=form.cleaned_data['email'])
                draft_booking.memberstatus = member
            except Member.DoesNotExist:
                draft_booking.memberstatus = None

            draft_booking.eventid = event
            draft_booking.referralid = referral
            draft_booking.save()
            
            messages.success(request, _(f'Thank you for your booking! Please pay the payment before {draft_booking.payment_expires_at.strftime("%d-%m-%y %H:%M")} WIB. Check your email for payment instructions.'))
            return redirect('booking_with_referral', event_id=event_id, referral_id=referral_id)
    else:
        form = DraftBookingForm()
        
    context = {
        'form': form,
        'event': event,
        'referralid': referral,
    }
    print("context", context)
    return render(request, 'booking.html', context)

def booking_without_referral(request, event_id):
    try:
        event = Class.objects.get(classid=event_id)
    except Class.DoesNotExist:
        raise Http404(_("Event doesn't exist"))
        
    if request.method == "POST":
        form = DraftBookingForm(request.POST)
        if form.is_valid():
            draft_booking = form.save(commit=False)
            try:
                member = Member.objects.get(emailmain=form.cleaned_data['email'])
                draft_booking.memberstatus = member
            except Member.DoesNotExist:
                draft_booking.memberstatus = None
            draft_booking.eventid = event
            draft_booking.save()
            
            messages.success(request, _(f'Thank you for your booking! Please pay the payment before {draft_booking.payment_expires_at.strftime("%d-%m-%y %H:%M")} WIB. Check your email for payment instructions.'))
            return redirect('booking_index', event_id=event_id)
    else:
        form = DraftBookingForm()

    context = {
        'form': form,
        'event': event,
        'referral': None,
    }
    return render(request, 'booking.html', context)

def event(request, event_id):
    event = Class.objects.get(classid=event_id)
    print("event", event)
    print("event_photo", event.classphoto)
    context = {
        'event': event,
    }
    return render(request, 'event.html', context)

booking/templates/booking.html
{% extends "_base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="mt-30 pt-20">
  <section class="bg-gray-100 min-h-screen">
    <div class="container py-12 mx-auto">
      <div class="flex flex-col lg:flex-row">
        <!-- Poster Image -->
        <div class="w-full lg:w-1/3">
          <div class="sticky top-24 mb-4"> <!-- Mengurangi jarak bawah di sini -->
            <img class="rounded-t-lg w-full h-auto max-w-xl" src="{{ event.classphoto }}" alt="{{ event.title }}" />
            <div class="flex max-w-xl justify-end">
              <a href="{% url 'booking_event' event.classid %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm py-2.5 mt-4">
                {% trans "More Details" %}
              </a>
            </div>
          </div>
        </div>

        <!-- Form Card -->
        <div class="w-full max-w-full">
          <div class="bg-white rounded-lg shadow p-8 mb-0">
            <h1 class="text-3xl font-bold mb-6 text-gray-900">{% trans "Event Booking" %}</h1>
            <hr class="mb-6">

            {% if messages %}
                {% for message in messages %}
                <div id="alert-3" class="flex items-center p-4 mb-4 text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
                    <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                    </svg>
                    <span class="sr-only">{% trans "Info" %}</span>
                    <div class="ms-3 text-sm font-medium">
                      {{ message }}
                    </div>
                    <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-green-50 text-green-500 rounded-lg focus:ring-2 focus:ring-green-400 p-1.5 hover:bg-green-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-green-400 dark:hover:bg-gray-700" data-dismiss-target="#alert-3" aria-label="{% trans 'Close' %}">
                      <span class="sr-only">{% trans 'Close' %}</span>
                      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                      </svg>
                    </button>
                  </div>
                {% endfor %}
            {% endif %}

            <form method="POST" class="space-y-6" action="{% if referralid %}{% url 'booking_with_referral' event.classid referralid %}{% else %}{% url 'booking_index' event.classid %}{% endif %}">
                {% csrf_token %}

                <div>
                    <label for="name" class="block mb-2 text-sm font-medium text-gray-900">{% trans "Name" %} *</label>
                    <input type="text" name="name" id="id_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" required>
                    {% if form.name.errors %}
                        {% for error in form.name.errors %}
                            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div>
                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900">{% trans "Email" %} *</label>
                    <input type="email" name="email" id="id_email" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" required>
                    {% if form.email.errors %}
                        {% for error in form.email.errors %}
                            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div>
                    <label for="phone" class="block mb-2 text-sm font-medium text-gray-900">{% trans "Phone" %} *</label>
                    <input type="number" name="phone" id="id_phone" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" required>
                    {% if form.phone.errors %}
                        {% for error in form.phone.errors %}
                            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div>
                    <label for="id_whatsapp" class="block mb-2 text-sm font-medium text-gray-900">{% trans "Is your phone number registered with telegram?" %} *</label>
                    <select name="telegram" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5">
                        <option value="True" {% if form.telegram %}selected{% endif %}>{% trans "Yes" %}</option>
                        <option value="False" {% if not form.telegram %}selected{% endif %}>{% trans "No" %}</option>
                    </select>
                    {% for error in form.telegram.errors %}
                        <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                    {% endfor %}
                </div>

                <div>
                    <label for="event" class="block mb-2 text-sm font-medium text-gray-900">{% trans "Event" %} *</label>
                    <input type="text" name="event" id="id_event" value="{{ event.classid }}" class="bg-gray-100 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5" readonly>
                    {% if form.event.errors %}
                        {% for error in form.event.errors %}
                            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>

                <div>
                    <label for="referralid" class="block mb-2 text-sm font-medium text-gray-900">{% trans "Referral" %}</label>
                    <input type="hidden" name="referralid" id="id_referralid" value="{{ referralid }}">
                    <input type="text" class="bg-gray-100 border border-gray-300 text-gray-900 text-sm rounded-lg block w-full p-2.5" value="{{ referralid.ktpname }}" readonly disabled>
                    {% if form.referralid.errors %}
                        {% for error in form.referralid.errors %}
                            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>

                <p class="block mb-2 text-sm font-medium text-red-500">{% trans "Note: Please fill the * required fields" %}</p>

                <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">{% trans "Submit" %}</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock %}

booking/templates/event.html
{% extends "_base.html" %}

{% load i18n %}

{% block content %}
<div class="bg-white h-7"></div>
<div class="container mx-auto px-2 pt-20">
    <div class="flex justify-center">
      <div class="shadow-lg shadow-gray-400 flex flex-col items-center bg-white border border-gray-200 rounded-lg md:flex-row h-dvh w-full max-w-7xl mt-10">
        <img class="object-cover rounded-t-lg h-96 md:h-96 md:rounded-none md:rounded-l-lg cursor-pointer" src="{{ event.classphoto }}" alt="{{ event.name }}" onclick="openModal(this.src)" />

        <div class="flex flex-col justify-between p-4 leading-normal">
          <h5 class="mb-2 ml-2 text-start text-xl font-bold tracking-tight text-gray-900 ml-10">{{ event.classname }}</h5>
          <ol class="ps-5 max-w-md space-y-1 text-gray-500 list-decimal list-inside">
              <li>
                  <span class="font-semibold text-gray-900"><i class="bi bi-clock"></i> {% trans "Time" %}:</span> <span class="text-gray-600">{{ event.startdate }} WIB</span>
              </li>
              <li>
                  <span class="font-semibold text-gray-900"><i class="bi bi-geo-alt"></i> {% trans "Location" %}:</span> <span class="text-gray-600">{{ event.vanue.location }}</span>
              </li>
              <li>
                  <span class="font-semibold text-gray-900"><i class="bi bi-currency-dollar"></i> {% trans "Cost" %}:</span> <span class="text-gray-600">Rp{{ event.cost }}</span>
              </li>
          </ol>
          
          
          <div class="mt-4 ml-2">
            <a href="{% url 'booking_index' event.classid %}" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300">
              {% trans "Submit" %}
              <svg class="w-3.5 h-3.5 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
</div>
<div class="bg-white h-12"></div>
{% endblock %}

booking/templates/payment_tele.html
{% load i18n %}
{% load static %}
{% block content %}

🎓 *BOOKING CONFIRMATION AND PAYMENT INSTRUCTIONS*

Dear *{{ name }}*,

Alhamdulillah, we have received a booking request with the details below:

📋 *Booking Details:*
• Booker Name: {{ name }}
• Event: {{ event_name }} 
• Location: {{ event_url }}
• Time: {{ event_time }}
• Referral: {{ referral_name }}

💳 *Payment Instructions*
To complete your booking, please make a payment to one of the following accounts:

1. Bank BCA:
   1234567890 - Salma Mardhiyah

2. Bank BRI:  
   0987654321 - Salma Mardhiyah

📤 *Send Payment Proof to:*
• Email: alphaseven.force@gmail.com
• WhatsApp: 081234567890

⚠️ *IMPORTANT NOTE:*
This offer is valid until:
• {{ payment_expires_at }} WIB (UTC+7)
• {{ payment_expires_at2 }} SGT (UTC+8)

Please ensure payment is completed and proof submitted within this period to secure your booking.

For further inquiries or assistance, don't hesitate to contact us.

Best regards,
*The Alpha Seven Force Team*

{% endblock %}